// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvdqxdobfnyiuzshcuia.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZHF4ZG9iZm55aXV6c2hjdWlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2OTUxNjIsImV4cCI6MjA3MTI3MTE2Mn0._6mNkKzLCqgSY7QFJ3s93qX6kKQplvwbEGkYDmpW3_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});